FROM php:8.1.17-fpm-alpine
LABEL maintainer="Nikesh Patel"
WORKDIR /var/web/public_html
RUN apk add --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/community/ --allow-untrusted gnu-libiconv
ENV LD_PRELOAD /usr/lib/preloadable_libiconv.so php

RUN docker-php-ext-install pdo

RUN apk update \
    && apk upgrade \
    && apk add --no-cache \
    git \
    curl \
    wget \
    unzip \
    xml

RUN apk add --no-cache --virtual .build-deps 

# Install composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Add xdebug
RUN pecl install xdebug \
    && docker-php-ext-enable xdebug

# Add sonar-scanner
COPY --from=sonarsource/sonar-scanner-cli:latest /opt/sonar-scanner /opt/sonar-scanner
