FROM php:8.1.17-zts-alpine3.17
LABEL maintainer="Nikesh Patel"
WORKDIR /var/web/public_html
RUN apk add --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/community/ --allow-untrusted gnu-libiconv
ENV LD_PRELOAD /usr/lib/preloadable_libiconv.so php

RUN docker-php-ext-install pdo

RUN apk update \
    && apk upgrade \
    && apk add --no-cache \
    git \
    curl \
    wget \
    unzip \
    xml

RUN apk add --no-cache --virtual .build-deps 

# Install composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Add xdebug
RUN pecl install xdebug \
    && docker-php-ext-enable xdebug


