FROM bitnami/wordpress
LABEL maintainer="Nikesh"

FROM debian:latest
LABEL maintainer="Nikesh Patel"

RUN apt-get update && DEBIAN_FRONTEND="noninteractive" apt-get install -y \
    git \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg-agent \
    software-properties-common \
    wget \
    gcc \
    make \
    bash \
    unzip \
    htop \
    man \
    vim \
    python3 \
    locate \
    lsb-release

RUN apt-get update

RUN curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -

RUN apt-get update

RUN apt-key fingerprint 0EBFCD88

RUN apt-get update

RUN add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/debian \
   $(lsb_release -cs) \
   stable"

RUN apt-get update && DEBIAN_FRONTEND="noninteractive" apt-get install -y \
    docker-ce \
    docker-ce-cli \
    containerd.io



RUN wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg

RUN echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" | tee /etc/apt/sources.list.d/php.list

RUN apt update

RUN wget -O composer-setup.php https://getcomposer.org/installer

RUN apt-get update && DEBIAN_FRONTEND="noninteractive" apt-get install -y \
  php7.4 \
  php7.4-mysql \ 
  php7.4-mbstring \
  php7.4-xml \
  php7.4-bcmath \
  php7.4-curl \
  php7.4-gd \
  php7.4-zip \
  php-cli \
  php7.4-dev 

RUN php composer-setup.php --install-dir=/usr/local/bin --filename=composer

RUN systemctl enable docker

